"""Language configuration and mapping utilities."""

# Simple language names to ISO codes (for speech-to-text)
LANGUAGE_TO_ISO = {
    "french": "fr",
    "english": "en",
    "spanish": "es",
    "german": "de",
    "italian": "it",
    "portuguese": "pt",
    "dutch": "nl",
    "polish": "pl",
    "russian": "ru",
    "chinese": "zh",
    "japanese": "ja",
    "korean": "ko",
    "arabic": "ar",
    "bengali": "bn",
    "afrikaans": "af",
    "greek": "el",
    "hindi": "hi",
    "malay": "ms",
    "serbian": "sr",
    "tagalog": "tl",
    "thai": "th",
    "turkish": "tr",
    "urdu": "ur",
    "hebrew": "he"
}

# Simple language names to BCP-47 codes (for text-to-speech)
LANGUAGE_TO_BCP47 = {
    "french": "fr-FR",
    "english": "en-US",
    "spanish": "es-ES",
    "german": "de-DE",
    "italian": "it-IT",
    "portuguese": "pt-PT",
    "dutch": "nl-NL",
    "polish": "pl-PL",
    "russian": "ru-RU",
    "chinese": "zh-CN",
    "japanese": "ja-JP",
    "korean": "ko-KR",
    "arabic": "ar-AR",
    "bengali": "bn-BN",
    "afrikaans": "af-ZA",
    "greek": "el-GR",
    "hindi": "hi-IN",
    "malay": "ms-MY",
    "serbian": "sr-RS",
    "tagalog": "tl-PH",
    "thai": "th-TH",
    "turkish": "tr-TR",
    "urdu": "ur-PK",
    "hebrew": "he-IL"
}

# Voice mappings for each supported BCP-47 language
TTS_VOICES = {
    "fr-FR": "fr-FR-Studio-D",
    "en-US": "en-US-Studio-M",
    "es-ES": "es-ES-Studio-B",
    "de-DE": "de-DE-Studio-B",
    "it-IT": "it-IT-Studio-B",
    "pt-PT": "pt-PT-Studio-B",
    "nl-NL": "nl-NL-Standard-B",
    "pl-PL": "pl-PL-Standard-B",
    "ru-RU": "ru-RU-Standard-B",
    "zh-CN": "zh-CN-Standard-B",
    "ja-JP": "ja-JP-Standard-B",
    "ko-KR": "ko-KR-Standard-B",
    "ar-AR": "ar-XA-Standard-B",
    "bn-BN": "bn-IN-Standard-B",
    "af-ZA": "af-ZA-Standard-A",
    "el-GR": "el-GR-Standard-A",
    "hi-IN": "hi-IN-Standard-B",
    "ms-MY": "ms-MY-Standard-A",
    "sr-RS": "sr-RS-Standard-A",
    "tl-PH": "fil-PH-Standard-A",
    "th-TH": "th-TH-Standard-A",
    "tr-TR": "tr-TR-Standard-B",
    "ur-PK": "ur-PK-Standard-A",
    "he-IL": "he-IL-Standard-A"
}

# Play.ai language mappings
PLAY_LANGUAGES = {
    "french": "french",
    "english": "english",
    "spanish": "spanish",
    "german": "german",
    "italian": "italian",
    "portuguese": "portuguese",
    "dutch": "dutch",
    "polish": "polish",
    "russian": "russian",
    "mandarin": "mandarin",
    "japanese": "japanese",
    "korean": "korean",
    "arabic": "arabic",
    "bengali": "bengali",
    "bulgarian": "bulgarian",
    "catalan": "catalan",
    "croatian": "croatian",
    "czech": "czech",
    "danish": "danish",
    "galician": "galician",
    "greek": "greek",
    "hebrew": "hebrew",
    "hindi": "hindi",
    "hungarian": "hungarian",
    "indonesian": "indonesian",
    "malay": "malay",
    "serbian": "serbian",
    "swedish": "swedish",
    "tagalog": "tagalog",
    "thai": "thai",
    "turkish": "turkish",
    "ukrainian": "ukrainian",
    "urdu": "urdu",
    "xhosa": "xhosa",
    "afrikaans": "afrikaans",
    "albanian": "albanian",
    "amharic": "amharic"
}

DEFAULT_LANGUAGE = "french"
DEFAULT_BCP47 = LANGUAGE_TO_BCP47[DEFAULT_LANGUAGE] 